/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/tracking/storeTrajectory 1

/run/initialize

/vis/open OGL
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts false
/vis/viewer/set/autoRefresh true
/vis/scene/endOfEventAction accumulate

/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0.0 0.0 -10.0 cm
/gps/pos/radius 1.0 cm
/gps/direction 0 0 1
/gps/ene/type Mono
/gps/ene/mono 2 MeV
